name: Deploy byeoltago-api to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      working-directory: backend/byeoltago-api
      run: ./gradlew bootJar

    - name: Decode private key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > my-key.pem
        chmod 600 my-key.pem

    - name: Copy JAR to EC2
      run: |
        scp -i my-key.pem -o StrictHostKeyChecking=no backend/byeoltago-api/build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app.jar

    - name: Deploy on EC2
      run: |
        ssh -i my-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker stop byeoltago-api || true
          sudo docker rm byeoltago-api || true
          sudo docker run -d --name byeoltago-api -p ${{ secrets.PORT }}:8080 \
            -v /home/${{ secrets.EC2_USER }}/app.jar:/app.jar \
            openjdk:17 java -jar /app.jar
        EOF
